# Imports

In [5]:
from ansatz import Ansatz

In [6]:
my_ansatz = Ansatz(n_qubits = 2, n_layers = 1)

In [7]:
from catboost import CatBoostRegressor
import numpy as np
import matplotlib.pyplot as plt

# Dataset definition

In [8]:
train_data = my_ansatz.generate_pairs(1024*100)
train_x, train_y = train_data

# Model

In [9]:
model = CatBoostRegressor(iterations=2000, loss_function='MultiRMSE')

In [10]:
model.fit(train_x, train_y, verbose=10)

0:	learn: 3.5772458	total: 168ms	remaining: 5m 35s
10:	learn: 3.1873931	total: 327ms	remaining: 59.2s
20:	learn: 2.9440719	total: 496ms	remaining: 46.7s
30:	learn: 2.7960740	total: 651ms	remaining: 41.4s
40:	learn: 2.7065233	total: 811ms	remaining: 38.7s
50:	learn: 2.6529929	total: 965ms	remaining: 36.9s
60:	learn: 2.6207426	total: 1.12s	remaining: 35.6s
70:	learn: 2.6012009	total: 1.28s	remaining: 34.7s
80:	learn: 2.5893098	total: 1.44s	remaining: 34s
90:	learn: 2.5817661	total: 1.59s	remaining: 33.3s
100:	learn: 2.5770104	total: 1.74s	remaining: 32.7s
110:	learn: 2.5736662	total: 1.89s	remaining: 32.2s
120:	learn: 2.5714291	total: 2.04s	remaining: 31.7s
130:	learn: 2.5699589	total: 2.2s	remaining: 31.4s
140:	learn: 2.5688301	total: 2.35s	remaining: 31s
150:	learn: 2.5680308	total: 2.51s	remaining: 30.7s
160:	learn: 2.5673037	total: 2.67s	remaining: 30.4s
170:	learn: 2.5668166	total: 2.82s	remaining: 30.2s
180:	learn: 2.5663096	total: 2.98s	remaining: 29.9s
190:	learn: 2.5659404	total

1580:	learn: 2.5460327	total: 23.9s	remaining: 6.32s
1590:	learn: 2.5459111	total: 24s	remaining: 6.17s
1600:	learn: 2.5458041	total: 24.2s	remaining: 6.02s
1610:	learn: 2.5456975	total: 24.3s	remaining: 5.87s
1620:	learn: 2.5456002	total: 24.5s	remaining: 5.72s
1630:	learn: 2.5454859	total: 24.6s	remaining: 5.57s
1640:	learn: 2.5453756	total: 24.8s	remaining: 5.42s
1650:	learn: 2.5452701	total: 24.9s	remaining: 5.27s
1660:	learn: 2.5451454	total: 25.1s	remaining: 5.12s
1670:	learn: 2.5450213	total: 25.2s	remaining: 4.96s
1680:	learn: 2.5449072	total: 25.4s	remaining: 4.81s
1690:	learn: 2.5447938	total: 25.5s	remaining: 4.66s
1700:	learn: 2.5446793	total: 25.7s	remaining: 4.51s
1710:	learn: 2.5445521	total: 25.8s	remaining: 4.36s
1720:	learn: 2.5444478	total: 26s	remaining: 4.21s
1730:	learn: 2.5443293	total: 26.1s	remaining: 4.06s
1740:	learn: 2.5442210	total: 26.3s	remaining: 3.91s
1750:	learn: 2.5441129	total: 26.4s	remaining: 3.76s
1760:	learn: 2.5440152	total: 26.6s	remaining: 3.6

In [12]:
test_data = my_ansatz.generate_pairs(512)
test_x, test_y = test_data
test_x = test_x[:10]
test_y = test_y[:10]
pred_y = model.predict(test_x)

In [13]:
from sklearn.metrics import mean_squared_error

In [14]:
mean_squared_error(test_y, pred_y)

2.1421405689960067

In [18]:
test_x

[array([ 0.30273561, -0.17078248,  0.05523593, -0.93602003]),
 array([0.08954333, 0.7756997 , 0.61440338, 0.1130507 ]),
 array([ 0.63410259,  0.36542742, -0.49694302, -0.46628782]),
 array([ 0.040986  , -0.07235624,  0.99653192, -0.00297591]),
 array([ 0.27934316,  0.44216778, -0.83952903, -0.14712599]),
 array([ 0.01862471, -0.89556453, -0.4429439 ,  0.0376563 ]),
 array([ 0.08274542, -0.86367795,  0.15084345, -0.47377194]),
 array([ 0.5470087 ,  0.37355292, -0.68771952, -0.29712214]),
 array([ 0.68459107,  0.10602966, -0.10166632, -0.7139725 ]),
 array([ 0.10112843,  0.52887775, -0.84024376, -0.06365364])]

In [28]:
[my_ansatz.apply_ansatz(i) for i in pred_y]

[array([ 0.31506781, -0.14809198,  0.0498431 , -0.93611789]),
 array([0.08246885, 0.77348164, 0.61995015, 0.10289238]),
 array([ 0.62737301,  0.37146931, -0.50740332, -0.45929896]),
 array([ 0.03584569, -0.06106142,  0.99748773, -0.0021943 ]),
 array([ 0.27630567,  0.44367355, -0.83994507, -0.14594945]),
 array([ 0.02270117, -0.8912699 , -0.45067403,  0.04489468]),
 array([ 0.07663189, -0.87112292,  0.14413807, -0.46313781]),
 array([ 0.55620243,  0.36488327, -0.6854439 , -0.29608398]),
 array([ 0.68926268,  0.10097337, -0.09792398, -0.71072656]),
 array([ 0.10757374,  0.54141877, -0.83089116, -0.07009635])]