# Imports

In [2]:
from ansatz import generate_pairs, apply_ansatz, n_qubits, n_theta

In [3]:
# %timeit generate_pairs

In [4]:
from sklearn.linear_model import LinearRegression
import numpy as np
import matplotlib.pyplot as plt

# Dataset definition

In [5]:
train_data = generate_pairs(512)
test_data = generate_pairs(512)
train_x, train_y = train_data

# Model

In [6]:
model = LinearRegression().fit(train_x, train_y)

In [9]:
y_pred = model.predict(train_x)

In [10]:
y_pred[0]

array([-0.04174695,  0.85834459, -0.05148678, -0.37255744,  0.1889666 ,
        0.03052983,  0.36233481,  0.37351012,  0.29279471,  0.25797569,
       -0.31736371,  0.0743459 ,  0.43517763,  0.64448463, -0.25958429])

In [11]:
train_y[0]

array([ 0.96033368, -0.45969455,  0.95308107, -1.5744345 ,  0.78491288,
        1.66122502, -0.73113941,  0.69466189,  2.56284003,  2.99478034,
        0.03998391,  1.48520483,  1.01694817, -2.3144396 , -1.91547352])

# Manual testing

In [135]:
model.eval()

#pair = generate_pairs(1)
#psi_true = torch.FloatTensor(pair[0])
#theta_true = torch.FloatTensor(pair[1])

psi_true, theta_true = next(iter(train_dataloader))

theta_true = theta_true.type(torch.cuda.FloatTensor).to(device)
psi_true = psi_true.type(torch.cuda.FloatTensor).to(device)

theta_pred = model(psi_true)
psi_pred = apply_ansatz(theta_pred.cpu().detach().numpy()[0])

psi_true = psi_true.cpu().detach().numpy()[0]
theta_pred = theta_pred.cpu().detach().numpy()[0]
theta_true = theta_true.cpu().detach().numpy()[0]

In [136]:
theta_true

array([ 0.13769707, -2.5084326 ,  0.8219688 , -0.57610226,  2.0594811 ,
        2.9071941 ,  2.5755737 ,  0.35429505, -0.7238956 , -0.3781726 ,
       -0.10268936, -0.45457563, -0.06386093,  0.05899178, -2.3657665 ],
      dtype=float32)

In [137]:
theta_pred

array([ 0.5854709 , -0.3857849 , -0.21052133, -0.07862001, -0.41407943,
        0.26970392,  0.5936242 , -1.391507  ,  0.846265  ,  0.22752911,
        0.04544682, -0.4745136 , -0.6196447 ,  0.05163885,  0.49995378],
      dtype=float32)

In [138]:
psi_true

array([ 0.03479514,  0.08244973,  0.00729992,  0.15860873,  0.10772569,
       -0.12523602, -0.03564199, -0.342554  , -0.03461746, -0.04581406,
       -0.00262007,  0.29865068, -0.00161154,  0.02781706,  0.04644791,
        0.28488517,  0.04958229,  0.09799421,  0.00790307, -0.0196984 ,
        0.04359046, -0.05697266, -0.02556625, -0.20651282, -0.05631585,
       -0.0549357 , -0.00175036,  0.73281974,  0.02457093, -0.00320661,
        0.03674925,  0.19531605], dtype=float32)

In [139]:
psi_pred

array([ 0.61152414,  0.01108412, -0.18773922, -0.04974421, -0.23130602,
       -0.05484798,  0.14137306,  0.0403255 , -0.06594379,  0.13419099,
       -0.14457441, -0.05076037,  0.04847438, -0.07169644,  0.04313973,
        0.01614893, -0.03978299, -0.05942503,  0.08367969,  0.02757193,
        0.02084326,  0.16014324, -0.14849347, -0.0495273 ,  0.29134964,
       -0.04848998, -0.02398435, -0.00140898, -0.51435881,  0.02019232,
        0.19002732,  0.04763556])